
config:
    # channel
    # // 渠道       平台   渠道号
    # // AppStore  iOS   c10000
    # // PC官网     安卓   c11000
    # // 华为       安卓   c11001
    # // 小米       安卓   c11002
    # // OPPO      安卓   c11003
    # // VIVO      安卓   c11004
    # // 应用宝     安卓   c11006
    # // 百度       安卓   c11007
    # // 360       安卓   c11008
    # // 阿里云     安卓   c11009
    # // 百度推广   安卓   c11010
    # // 分享好友   安卓    c11011
    # // 酷安       安卓   c11012
    # //其他自定义  安卓    11101
    # //其他自定义  安卓    11102
    # //其他自定义  安卓    11103
    # //其他自定义  安卓    11104
    # //其他自定义  安卓    11105
    # //其他自定义  安卓    11106
    # //其他自定义  安卓    12***
    
    channel: 'c88888'
    isDebug: true
